version: "3.8"

services:
  smartrenroll:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=smartenroll_db
    volumes:
      - ./src:/src
      - ./package.json:/usr/src/app/package.json- .:/usr/src/app
    command: wix dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: smartenroll_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - smartrenroll

volumes:
  pgdata:
