name: Docker Image CI

on:
  push:
    branches: 
      - main
      - staging
      - uat
  pull_request:
      - main
      - staging
      - uat

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag smartenroll:$(date +%s)
