name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
      - uat
  pull_request:
    branches:
      - main
      - staging
      - uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t smartrenroll:latest .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Run tests
        run: npm test

  deploy-uat:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/uat'

    steps:
      - name: Deploy to UAT Server
        run: |
          ssh user@your-uat-server-ip "docker pull smartrenroll:latest && docker-compose up -d"

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy to Staging Server
        run: |
          ssh user@your-staging-server-ip "docker pull smartrenroll:latest && docker-compose up -d"

  deploy-production:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production Server
        run: |
          ssh user@your-production-server-ip "docker pull smartrenroll:latest && docker-compose up -d"
